config/routes.rb
Rails.application.routes.draw do

  root   'homes#index'
  get    'feedback', to: 'homes#new'
  post   'feedback', to: 'homes#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
    resources :statistics, only: :index
    resources :feedbacks
    resources :stores
    resources :cities do
      get   'stores', to: 'cities#stores'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_main_navbar.html.erb
<div class="navbar navbar-expand-md navbar-dark">
  <div class="navbar-brand">
    <a href="" class="d-inline-block">
      <img src="" alt="">
    </a>
  </div>
  <div class="d-md-none">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
      <i class="icon-tree5"></i>
    </button>
    <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
      <i class="icon-paragraph-justify3"></i>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="navbar-mobile">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="navbar-nav-link sidebar-control sidebar-main-toggle
          d-none d-md-block">
          <i class="icon-paragraph-justify3"></i>
        </a>
      </li>
    </ul>
    <span class="badge bg-success ml-md-3 mr-md-auto">Online</span>
    <ul class="navbar-nav">
      <li class="nav-item dropdown dropdown-user">
        <a href="#" class="navbar-nav-link d-flex align-items-center
          dropdown-toggle" data-toggle="dropdown">
          <%= image_tag "avatar-none.png", class: "rounded-circle mr-2", height: "34" %>
          <span><%= @current_user.name %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to  logout_path, method: :delete, class: "dropdown-item" do %>
            <i class="icon-switch2"></i><%= t('button.session.destroy') %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_main_sidebar.html.erb
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">
  <div class="sidebar-mobile-toggler text-center">
    <a href="#" class="sidebar-mobile-main-toggle">
      <i class="icon-arrow-left8"></i>
    </a>
    <a href="#" class="sidebar-mobile-expand">
      <i class="icon-screen-full"></i>
      <i class="icon-screen-normal"></i>
    </a>
  </div>
  <div class="sidebar-content">
    <div class="sidebar-user">
      <div class="card-body">
        <div class="media">
          <div class="mr-3">
            <a href="#">
              <%= image_tag "avatar-none.png", class: "rounded-circle", height: "38", width: "38" %>
            </a>
          </div>
          <div class="media-body">
            <div class="media-title font-weight-semibold"><%= @current_user.name %></div>
            <div class="font-size-xs opacity-50">
            </div>
          </div>
          <div class="ml-3 align-self-center">
            <a href="#" class="text-white"><i class="icon-cog3"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sidebar-mobile">
      <ul class="nav nav-sidebar" data-nav-type="accordion">
        <li class="nav-item">
          <%= link_to admin_statistics_path, class: "nav-link" do %>
            <i class="icon-chart"></i><span><%= t('button.main.statistic') %></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_feedbacks_path, class: "nav-link" do %>
            <i class="icon-pen"></i><span><%= t('button.main.feedback') %></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_stores_path, class: "nav-link" do %>
            <i class="icon-home"></i><span><%= t('button.main.store') %></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_cities_path, class: "nav-link" do %>
            <i class="icon-location3"></i><span><%= t('button.main.city') %></span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>