config/routes.rb
Rails.application.routes.draw do

  root   'homes#index'
  get    'feedback', to: 'homes#new'
  post   'feedback', to: 'homes#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
    resources :statistics, only: :index
    resources :feedbacks
    resources :stores
    resources :cities do
      get   'stores', to: 'cities#stores'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many   :feedbacks
  delegate :name, to: :city, prefix: true

  enum status: [:activity, :repair, :close]

  scope :_city_id, -> (city_id) { where(city_id: city_id) }

  validates :name, :address, :phone, :city_id, presence: true
  validates :address, uniqueness: true
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::AdminController

  def index
    respond_to do |format|
      format.json do
        render json: {
          stores: Store._city_id(params[:city_id])
        }.to_json
      end
      format.html do
        @stores = Store.includes(:city, :feedbacks)
      end
    end
  end

  def new
    @store = Store.new
    @cities = City.all
  end

  def create
    @store = Store.new(store_params.merge(user_id: @current_user.id))
    respond_to do |format|
      format.js {
        if @store.valid?
          @store.save
          @messages = [t('messages_alert.store.create.success')]
        else
          @messages = [:name, :address, :phone, :city_id, :status].map do |param|
            unless @store.errors.messages[param][0].blank?
              "#{ Store.human_attribute_name("#{param}")} #{@store.errors.messages[param][0]}"
            else
              ""
            end
          end
        end
      }
    end
  end

  def edit
    @store = Store.find_by(id: params[:id])
    @cities = City.all
  end

  def update
    respond_to do |format|
      format.js {
        @store = Store.find_by(id: params[:id])
        if @store.update(store_params)
          @messages = [t('messages_alert.store.update.success')]
        else
          @messages = [:name, :address, :phone, :city_id, :status].map do |param|
            unless @store.errors.messages[param][0].blank?
              "#{ Store.human_attribute_name("#{param}")} #{@store.errors.messages[param][0]}"
            else
              ""
            end
          end
        end
      }
    end
  end

   private
    def store_params
      params.require(:store).permit(:name, :address, :phone, :city_id, :status)
    end
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
  def get_selection_status
    Settings.store_status.map do |r|
      [I18n.t("status.#{r}"), r.to_sym]
    end
  end

  def badge_class(text)
    check = text
    case check
    when 'close'
      'badge-danger'
    when 'repair'
      'badge-info'
    else
      'badge-success'
    end
  end
end

app/views/admin/stores/_form_edit.html.erb
<%= form_for(@store, url: admin_store_path(@store), remote: true) do |f| %>
  <div class="modal-body">
    <div class="form-group row">
      <%= f.label :name, Store.human_attribute_name(:name),
          class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :phone, Store.human_attribute_name(:phone),
          class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.text_field :phone, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :address, Store.human_attribute_name(:address),
          class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :city_id, Store.human_attribute_name(:city),
        class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.select :city_id, @cities.collect { |e| [e.name, e.id] },
          { include_blank: t('select.city')},
          class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :status, Store.human_attribute_name(:status),
        class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.select :status, get_selection_status, {}, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button(:submit, class: "btn btn-primary") do %>
      <i class="icon-coins"></i>
    <% end %>
  </div>
<% end %>

app/views/admin/stores/_form_new.html.erb
<%= form_for(@store, url: admin_stores_path, remote: true) do |f| %>
  <div class="modal-body">
    <div class="form-group row">
      <%= f.label :name, Store.human_attribute_name(:name),
          class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :phone, Store.human_attribute_name(:phone),
          class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.text_field :phone, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :address, Store.human_attribute_name(:address),
          class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :city_id, Store.human_attribute_name(:city),
        class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.select :city_id, @cities.collect { |e| [e.name, e.id] },
          { include_blank: t('select.city')},
          class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :status, Store.human_attribute_name(:status),
        class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.select :status, get_selection_status, {}, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button(:submit, class: "btn btn-primary") do %>
      <i class="icon-coins"></i>
    <% end %>
  </div>
<% end %>

app/views/admin/stores/_page_header.html.erb
<div class="page-header page-header-light">
  <div class="page-header-content header-elements-md-inline">
    <div class="page-title d-flex">
      <h4>
        <i class="icon-arrow-left52 mr-2"></i>
        <span class="font-weight-semibold"><%= t('text.manager') %></span>
        <%= t('text.store') %>
      </h4>
      <a href="#" class="header-elements-toggle text-default d-md-none">
        <i class="icon-more"></i></a>
    </div>
    <div class="header-elements d-none">
      <div class="d-flex justify-content-center">
        <%= link_to new_admin_store_path, class: "btn btn-link btn-float", remote: true do %>
          <i class="icon-add"></i>
          <span><%= t('title.store.register') %></span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
    <div class="d-flex">
      <div class="breadcrumb">
        <%= link_to root_path, class: "breadcrumb-item" do %>
          <i class="icon-home2 mr-2"></i><%= t('button.main.home') %>
        <% end %>
        <%= link_to t('button.main.store'), admin_stores_path, class: "breadcrumb-item" %>
        <span class="breadcrumb-item active"><%= title %></span>
      </div>
      <a href="#" class="header-elements-toggle text-default d-md-none">
        <i class="icon-more"></i></a>
    </div>
  </div>
</div>

app/views/admin/stores/_store.html.erb
<tr>
  <td><%= store.id %></td>
  <td><%= store.name %></td>
  <td><%= store.address %></td>
  <td><%= store.phone %></td>
  <td><%= store.city_name %></td>
  <td>
    <%= content_tag("span", t("status.#{store.status}"),
      class: "badge #{badge_class(store.status)}") %>
  </td>
  <td class="text-center">
    <div class="list-icons">
      <div class="dropdown">
        <a href="#" class="list-icons-item" data-toggle="dropdown">
          <i class="icon-menu9"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to t('button.action.edit'), edit_admin_store_path(store), remote: true,
            class: "dropdown-item text-success" %>
        </div>
      </div>
    </div>
  </td>
</tr>

app/views/admin/stores/create.js.erb
<% @messages.each do |m| %>
  if ('<%= m %>' !== '') {
    new PNotify({
      title: 'Thông báo',
      text: '<%= m %>',
      type: 'bg-primary border-primary'
    });

    if ('<%= m %>' === '<%= t("messages_alert.store.create.success") %>') {
      setTimeout(function(){
        location.reload();
      }, 1000);
    }
  };
<% end %>

app/views/admin/stores/edit.js.erb
$('.form-modal').html("<%= j render('form_edit') %>");
$('#modal_store_edit').modal('show');

app/views/admin/stores/index.html.erb
<div class="content-wrapper">
  <%= render 'page_header', title: t('title.general.list') %>
  <div class="content">
    <div class="card">
      <div class="card-header header-elements-inline">
        <h5 class="card-title"><%= t('title.store.list') %></h5>
        <div class="header-elements">
          <div class="list-icons">
            <a class="list-icons-item" data-action="collapse"></a>
            <a class="list-icons-item" data-action="reload"></a>
          </div>
        </div>
      </div>
      <table class="table datatable-basic">
        <thead>
          <tr>
            <th><%= Store.human_attribute_name("id") %></th>
            <th><%= Store.human_attribute_name("name") %></th>
            <th><%= Store.human_attribute_name("address") %></th>
            <th><%= Store.human_attribute_name("phone") %></th>
            <th><%= Store.human_attribute_name("city") %></th>
            <th><%= Store.human_attribute_name("status") %></th>
            <th class="text-center"><%= t('table.action') %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @stores %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="modal_store" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t("title.store.register") %></h5>
        <button type="button" class="close" id="close-export"
          data-dismiss="modal">&times;</button>
      </div>
      <div class="form-modal">
      </div>
    </div>
  </div>
</div>
<div id="modal_store_edit" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t("title.store.edit") %></h5>
        <button type="button" class="close" id="close-export"
          data-dismiss="modal">&times;</button>
      </div>
      <div class="form-modal">
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    DatatableBasic.init();
    InputsBasic.init();
  });
</script>

app/views/admin/stores/new.js.erb
$('.form-modal').html("<%= j render('form_new') %>");
$('#modal_store').modal('show');

app/views/admin/stores/update.js.erb
<% @messages.each do |m| %>
  if ('<%= m %>' !== '') {
    new PNotify({
      title: 'Thông báo',
      text: '<%= m %>',
      type: 'bg-primary border-primary'
    });

    if ('<%= m %>' === '<%= t("messages_alert.store.update.success") %>') {
      setTimeout(function(){
        location.reload();
      }, 1000);
    }
  };
<% end %>