config/routes.rb
Rails.application.routes.draw do

  root   'homes#index'
  get    'feedback', to: 'homes#new'
  post   'feedback', to: 'homes#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
    resources :statistics, only: :index
    resources :feedbacks
    resources :stores
    resources :cities do
      get   'stores', to: 'cities#stores'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  has_many :stores
  belongs_to :user

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/admin/cities_controller.rb
class Admin::CitiesController < Admin::AdminController

  skip_before_action :require_login, only: :stores

  def index
    @cities = City.all
  end

  def stores
    respond_to do |format|
      format.json do
        render json: {
          stores: Store._city_id(params[:city_id])
        }.to_json
      end
    end
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params.merge(user_id: @current_user.id))
    respond_to do |format|
      format.js {
        if @city.valid?
          @city.save
          @messages = t('messages_alert.city.create.success')
        else
          @messages = "#{ City.human_attribute_name("name")} #{@city.errors.messages[:name][0]}"
        end
      }
    end
  end

  def edit
    @city = City.find_by(id: params[:id])
  end

  def update
    respond_to do |format|
      format.js {
        @city = City.find_by(id: params[:id])
        if @city.update(city_params)
          @messages = t('messages_alert.city.update.success')
        else
          @messages = t('messages_alert.city.update.failed')
        end
      }
    end
  end



  private
    def city_params
      params.require(:city).permit(:name)
    end
end

app/views/admin/cities/_city.html.erb
<tr>
  <td class="text-center"><%= city.id %></td>
  <td class="text-center"><%= city.name %></td>
  <td class="text-center"><%= city.stores.size %></td>
  <td class="text-center">
    <div class="list-icons">
      <div class="dropdown">
        <a href="#" class="list-icons-item" data-toggle="dropdown">
          <i class="icon-menu9"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to t('button.action.edit'), edit_admin_city_path(city), remote: true,
            class: "dropdown-item text-success" %>
        </div>
      </div>
    </div>
  </td>
</tr>

app/views/admin/cities/_form_edit.html.erb
<%= form_for(@city, url: admin_city_path(@city), remote: true) do |f| %>
  <div class="modal-body">
    <div class="form-group row">
      <%= f.label :name, City.human_attribute_name(:name),
          class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button(:submit, class: "btn btn-primary") do %>
      <i class="icon-coins"></i>
    <% end %>
  </div>
<% end %>

app/views/admin/cities/_form_new.html.erb
<%= form_for(@city, url: admin_cities_path, remote: true) do |f| %>
  <div class="modal-body">
    <div class="form-group row">
      <%= f.label :name, City.human_attribute_name(:name),
          class: "col-form-label col-lg-3" %>
      <div class="col-lg-5">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button(:submit, class: "btn btn-primary") do %>
      <i class="icon-coins"></i>
    <% end %>
  </div>
<% end %>

app/views/admin/cities/_page_header.html.erb
<div class="page-header page-header-light">
  <div class="page-header-content header-elements-md-inline">
    <div class="page-title d-flex">
      <h4>
        <i class="icon-arrow-left52 mr-2"></i>
        <span class="font-weight-semibold"><%= t('text.manager') %></span>
        <%= t('text.city') %>
      </h4>
      <a href="#" class="header-elements-toggle text-default d-md-none">
        <i class="icon-more"></i></a>
    </div>
    <div class="header-elements d-none">
      <div class="d-flex justify-content-center">
        <%= link_to new_admin_city_path, class: "btn btn-link btn-float", remote: true do %>
          <i class="icon-add"></i>
          <span><%= t('title.city.register') %></span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
    <div class="d-flex">
      <div class="breadcrumb">
        <%= link_to root_path, class: "breadcrumb-item" do %>
          <i class="icon-home2 mr-2"></i><%= t('button.main.home') %>
        <% end %>
        <%= link_to t('button.main.city'), admin_cities_path, class: "breadcrumb-item" %>
        <span class="breadcrumb-item active"><%= title %></span>
      </div>
      <a href="#" class="header-elements-toggle text-default d-md-none">
        <i class="icon-more"></i></a>
    </div>
  </div>
</div>

app/views/admin/cities/create.js.erb
if ('<%= @messages %>') {
  new PNotify({
    title: 'Thông báo',
    text: '<%= @messages %>',
    type: 'bg-primary border-primary'
  });

  if ('<%= @messages %>' === '<%= t("messages_alert.city.create.success") %>') {
    setTimeout(function(){
      location.reload();
    }, 1000);
  }
};

app/views/admin/cities/edit.js.erb
$('.form-modal').html("<%= j render('form_edit') %>");
$('#modal_city_edit').modal('show');

app/views/admin/cities/index.html.erb
<div class="content-wrapper">
  <%= render 'page_header', title: t('title.general.list') %>
  <div class="content">
    <div class="card">
      <div class="card-header header-elements-inline">
        <h5 class="card-title"><%= t('title.city.list') %></h5>
        <div class="header-elements">
          <div class="list-icons">
            <a class="list-icons-item" data-action="collapse"></a>
            <a class="list-icons-item" data-action="reload"></a>
          </div>
        </div>
      </div>
      <table class="table datatable-basic">
        <thead>
          <tr>
            <th class="text-center"><%= City.human_attribute_name("id") %></th>
            <th class="text-center"><%= City.human_attribute_name("name") %></th>
            <th class="text-center"><%= City.human_attribute_name("quantity") %></th>
            <th class="text-center"><%= t('table.action') %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @cities %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="modal_city" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t("title.city.register") %></h5>
        <button type="button" class="close" id="close-export"
          data-dismiss="modal">&times;</button>
      </div>
      <div class="form-modal">
      </div>
    </div>
  </div>
</div>
<div id="modal_city_edit" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t("title.city.edit") %></h5>
        <button type="button" class="close" id="close-export"
          data-dismiss="modal">&times;</button>
      </div>
      <div class="form-modal">
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    DatatableBasic.init();
    InputsBasic.init();
  });
</script>

app/views/admin/cities/new.js.erb
$('.form-modal').html("<%= j render('form_new') %>");
$('#modal_city').modal('show');

app/views/admin/cities/update.js.erb
if ('<%= @messages %>') {
  new PNotify({
    title: 'Thông báo',
    text: '<%= @messages %>',
    type: 'bg-primary border-primary'
  });

  if ('<%= @messages %>' === '<%= t("messages_alert.city.update.success") %>') {
    setTimeout(function(){
      location.reload();
    }, 1000);
  }
};