config/routes.rb
Rails.application.routes.draw do

  root   'homes#index'
  get    'feedback', to: 'homes#new'
  post   'feedback', to: 'homes#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
    resources :statistics, only: :index
    resources :feedbacks
    resources :stores
    resources :cities do
      get   'stores', to: 'cities#stores'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  include Rating
  require 'json'

  skip_before_action :require_login, only: [:index, :new, :create]

  def index
    if t("messages_alert.session.login").include?(params[:login]&.to_sym)
      @message = t("messages_alert.session.login.#{params[:login]}")
    elsif t("messages_alert.session.logout").include?(params[:logout]&.to_sym)
      @message = t("messages_alert.session.logout.#{params[:logout]}")
    end
  end

  def new
    @feedback = Feedback.new
    @cities = City.all
    @stores = Store.all
  end

  def create
    feedback = Feedback.new(feedback_params)
    respond_to do |format|
      format.js {
        if feedback.valid?
          return @messages = [t('messages_alert.feedback.create.max')] if feedback.content.length() > 250
          a = system("python3 lib/python/predict.py '#{feedback.content}'")
          rating_predict = File.read("lib/python/data/result.txt")
          rating = calculate(rating_predict.to_f)
          if rating != 0
            feedback.rating = rating
            feedback.save
            @messages = [t('messages_alert.feedback.create.success')]
            ThanksMailer.thanks(feedback.email, feedback.name).deliver_now
          else
            @messages = [t('messages_alert.feedback.create.spam')]
          end
        else
          @messages = [:name, :email, :content, :store_id].map do |param|
            unless feedback.errors.messages[param][0].blank?
              "#{ Feedback.human_attribute_name("#{param}")} #{feedback.errors.messages[param][0]}"
            else
              ""
            end
          end
        end
      }
    end
  end

  private
    def feedback_params
      params.require(:feedback).permit(:name, :email, :content, :store_id)
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/shared/_footer.html.erb
<footer id="footer" class="dark" style="">
  <div id="copyrights" class="nobg">
    <div class="container clearfix">
      <div class="col_half nobottommargin">
      </div>
      <div class="col_half col_last nobottommargin">
        <div class="copyrights-menu copyright-links fright clearfix">
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/homes/shared/_header.html.erb
<header id="header" class="static-sticky transparent-header split-menu clearfix">
  <div id="header-wrap" class="background-sketch-header">
    <div class="container clearfix">
      <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>
      <div id="logo">
        <a href="/" class="standard-logo">
        </a>
        <a href="/" class="retina-logo">
        </a>
      </div>
      <nav id="primary-menu" class="with-arrows clearfix">
        <ul>
          <li><a href="/"><div><%= t('main_user.bar.home') %></div></a></li>
          <li><a href="/feedback"><div><%= t('main_user.bar.feedback') %></div></a></li>
        </ul>
        <ul>
          <% unless logged_in? %>
            <li>
              <%= link_to login_path, class: "color" do %>
                <div>
                  <%= t('main_user.bar.login') %>
                </div>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to admin_stores_path do %>
                <div>
                  <%= t('main_user.bar.manager') %>
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete, class: "color" do %>
                <%= t('main_user.bar.logout') %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>